// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    Grid: typeof import('./components/Grid/index.vue')['default']
    GridItem: typeof import('./components/Grid/components/GridItem.vue')['default']
    Hamburger: typeof import('./components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconSelect: typeof import('./components/IconSelect/index.vue')['default']
    Pagination: typeof import('./components/SimpleTable/components/Pagination.vue')['default']
    ParentView: typeof import('./components/ParentView/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SchemaFormDatePicker: typeof import('./components/SearchForm/modules/SchemaFormDatePicker.vue')['default']
    SchemaFormInput: typeof import('./components/SearchForm/modules/SchemaFormInput.vue')['default']
    SchemaFormSelect: typeof import('./components/SearchForm/modules/SchemaFormSelect.vue')['default']
    SearchForm: typeof import('./components/SearchForm/index.vue')['default']
    SearchFormItem: typeof import('./components/SearchForm/components/SearchFormItem.vue')['default']
    SimpleDialog: typeof import('./components/SimpleDialog/index.vue')['default']
    SimpleTable: typeof import('./components/SimpleTable/index.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/index.vue')['default']
    TableColumn: typeof import('./components/SimpleTable/components/TableColumn.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
